### ISSUE TITLE
Responsive issue with Settings Dialog box

### ISSUE THREAD

**Issue by meghsohor** [binary-com/SmartCharts#1103]
Hi @ashkanx, I found a responsive issue with **Settings Dialog box** in mobile devices:

![image](https://user-images.githubusercontent.com/13042947/93780058-80af3680-fc49-11ea-8646-bcc7379c74e4.png)

**Comment by shayan-binary-2** [comment]
@meghsohor thank you for reaching out. yes that is correct, currently, we are not supporting responsive design except `chart type interval` and `market selector`.

**Comment by meghsohor** [comment]
Thank you for your response @shayan-binary-2
