### ISSUE TITLE
SmartCharts Custom Widgets

### ISSUE THREAD

**Issue by mshery** [binary-com/SmartCharts#1128]
#In the smart chart, we want to add our custom pair of market currency widgets but I didn't found in the documents where should I implement our pair and get the current market price & time that show in the chart. in the chart, they have their own widgets which show the market price that changes every second but in the app code, we didn't found. Please give me the right way which we follow and implement this logic in our website that uses this SmartChart. @jy-binary @ashkanx @ashkanx 

-

**Comment by mshery** [comment]
> #In the smart chart, we want to add our custom pair of market currency widgets but I didn't found in the documents where should I implement our pair and get the current market price & time that show in the chart. in the chart, they have their own widgets which show the market price that changes every second but in the app code, we didn't found. Please give me the right way which we follow and implement this logic in our website that uses this SmartChart. @jy-binary @ashkanx @ashkanx

**Comment by shayan-binary-2** [comment]
@mshery  Market should come from the API and we call is `activeSymbol` you can follow this name to understand the detail of follow
