### ISSUE TITLE
No files matching the pattern

### ISSUE THREAD

**Issue by shinauri** [binary-com/SmartCharts#1172]
On windows 10 Pro, any npm commands produces Error: No files matching the pattern "C:\Users\User\Desktop\projects\charts\SmartCharts\**\*.s?(c|a)ss" were found.
    at C:\Users\User\Desktop\projects\charts\SmartCharts\node_modules\stylelint\lib\standalone.js:207:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

but on mac  everything compiles fine.

**Comment by shayan-binary-2** [comment]
@shinauri from the above message, it seems there is an issue with the Stylelint on the windows. so I don't think it would be related to SmartChart.
